### ISSUE TITLE
Possible to list Youtube comments ?

### ISSUE THREAD

**Issue by GunGunGun** [CogentRedTester/mpv-scroll-list#5]
I'm trying to write a scroll list to display and read through Youtube comments, is this possible with this plugin or a full plugin is needed because so far MPV doesn't provide API to get Youtube comments, but yt-dlp does with --write-comments but I don't know if it's possible to interact with this plugin after that ?

**Comment by CogentRedTester** [comment]
It is possible, once you've grabbed the comments using mpv's [subpocess](https://mpv.io/manual/master/#command-interface-subprocess) command you just create item tables with the contents that you want to see. You can see here for a simple example: [chapter-list](https://github.com/CogentRedTester/mpv-scroll-list/blob/master/examples/chapter-list.lua).

Scroll-list can create the scrollable list for you, but fetching and interpreting the comments is up to you.
